title: "International Cuneiform Languages Retreat"
description: "Web hub for the cuneiform language retreat"
url: http://sohnyrin.github.com/
baseurl: "lang-retreat/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Schedule
   url: /schedule
 - title: Participants
   url: /participants
 - title: Contact
   url: /contact
 - title: Venue
   url: /venue
social:
   email: epageperron@gmail.com

google_analytics: ""
